# Generated by Django 2.2.7 on 2019-11-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='email',
            field=models.CharField(default='anurag@gmail.com', max_length=100),
            preserve_default=False,
        ),
    ]
