# Generated by Django 2.2.7 on 2019-11-24 10:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_host_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100)),
                ('guest_phone', models.IntegerField()),
                ('guest_mail', models.EmailField(max_length=100)),
                ('checked_in', models.BooleanField()),
                ('check_in_time', models.DateTimeField(default=datetime.datetime(2019, 11, 24, 15, 41, 49, 369954))),
                ('checked_out_time', models.DateTimeField(blank=True, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Meeting')),
            ],
        ),
    ]
