# Generated by Django 2.2.7 on 2019-11-24 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='check_in_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 24, 16, 49, 2, 751995)),
        ),
        migrations.AlterField(
            model_name='guest',
            name='checked_in',
            field=models.BooleanField(default=True),
        ),
    ]
