# Generated by Django 2.2.7 on 2019-11-24 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191124_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='token',
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guest',
            name='check_in_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 24, 17, 33, 41, 915743)),
        ),
    ]
